---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Terragrunt Apply
permissions: { contents: read }

on:
  workflow_dispatch: {}
  push:
    branches: ["main"]
    paths:
      - root.hcl
      - infrastructure/**
      - modules/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  TERRAGRUNT_NON_INTERACTIVE: "true"
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

jobs:
  terragrunt-apply:
    runs-on: infra-runners
    environment: homelab
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Setup mise
        uses: jdx/mise-action@d16887ba50704baed7de72bd1e82e04391e4457a # v3.5.0

      - name: Load Secrets
        uses: ./.github/actions/load-secrets
        with:
          op-service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Terragrunt Init
        run: terragrunt init --all -upgrade

      - name: Terragrunt Apply
        run: terragrunt apply --all -auto-approve -no-color
