---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Terragrunt Lint
permissions: { contents: read }

on:
  push: {}
  workflow_dispatch:
    inputs:
      fix:
        description: Automatically fix formatting issues
        default: false
        required: false
        type: boolean

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token}}

      - name: Setup mise
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1

      - name: Run tofu fmt
        run: |
          if [[ "${{ inputs.fix }}" == "true" ]]; then
            mise exec -- tofu fmt -recursive
          else
            mise exec -- tofu fmt -recursive -check
          fi

      - name: Run terragrunt fmt
        run: |
          if [[ "${{ inputs.fix }}" == "true" ]]; then
            mise exec -- terragrunt hcl format
          else
            mise exec -- terragrunt hcl format --check
          fi

      - name: Commit and Push Changes
        if: ${{ inputs.fix == true }}
        run: |
          git config --global user.name "mr-borboto[bot]"
          git config --global user.email "170036086+mr-borboto[bot]@users.noreply.github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: format tofu and terragrunt files"
            git push
          fi
