---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Terragrunt Apply
permissions: { contents: read }

on:
  workflow_dispatch: {}
  push:
    branches: ["main"]
    paths:
      - root.hcl
      - infrastructure/**
      - modules/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  TERRAGRUNT_NON_INTERACTIVE: "true"
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

jobs:
  terragrunt-apply:
    runs-on: infra-runners
    environment: homelab
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup mise
        uses: jdx/mise-action@be3be2260bc02bc3fbf94c5e2fed8b7964baf074 # v3.4.0

      - name: Load Secrets
        uses: ./.github/actions/load-secrets
        with:
          op-service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Terragrunt Init
        run: terragrunt init --all -upgrade

      - name: Terragrunt Apply
        run: terragrunt apply --all -auto-approve -no-color
