---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Terragrunt Apply
permissions: { contents: read }

on:
  workflow_dispatch: {}
  push:
    branches: ["main"]
    paths:
      - root.hcl
      - infrastructure/**
      - modules/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  TERRAGRUNT_NON_INTERACTIVE: "true"
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

jobs:
  terragrunt-apply:
    runs-on: infra-runners
    environment: homelab
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup mise
        uses: jdx/mise-action@c53b9236f0b3370f31520f8b142f141256d839c6 # v3.6.0

      - name: Load Secrets
        uses: ./.github/actions/load-secrets
        with:
          op-service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Terragrunt Init
        run: terragrunt init --all -upgrade

      - name: Terragrunt Apply
        run: terragrunt apply --all -auto-approve -no-color
